### ISSUE TITLE
More detailed description

### ISSUE THREAD

**Issue by operatorone** [ivoschimani/loadscripts#1]
Hi there,

would it be possible to get a more detailed description? What does the extension do specifically? Are also the scripts of other extensions possible to load at a different position?

Cheers, operatorone

**Comment by ivoschimani** [comment]
Hi operatorone,

a small readme is added to the Repo.

**Comment by operatorone** [comment]
Hi @ivoschimani,

that's outstanding. Thanks a lot for the readme.
